### ISSUE TITLE
 Istio CNI for Istio-1.1 Readiness Tracker

### ISSUE THREAD

**Issue by tiswanso** [istio/cni#51]
Using this issue as a landing spot to track readiness for Istio release 1.1.  The following work items are mandatory for 1.1. 

**Repo Issues**
1. [X]  Owners permissions--not everyone in owners file have permissions to do "owners" stuff
   1. [X] assign issues, assign reviewers
   1. [X] approve PRs
   1. [X] merge PRs
1. [X] CircleCI project hookup.  No cni sub-project under istio in CircleCI so no jobs are firing (Costin working) - Done jobs running now
1. [X] DCO check never completes (remove DCO check) - Removed the DCO check 

**Release Readiness Items**
1. [X] hosting "release" candidate docker images
    1. [X] nightly circleci job will build & push to docker.io -- #53 
    1. [X] keep decoupled--figure out how to generate & host release artifacts (container images, trigger helm chart publish) https://github.com/istio/istio/pull/9973
1. [X] hosting "release" helm chart
   1. [X] istio-cni chart packaged by https://github.com/istio/istio.io/blob/master/scripts/grab_charts.sh  (https://github.com/istio/istio.io/pull/2827)
   1. [X]  istio/istio github_release.sh package helm charts (https://github.com/istio/istio/pull/9496)
            - Needs to be a specific tag need coordination on tag value
1. [X] Prow jobs
   1. [X] istio/istio change triggered  -  Need PRs https://github.com/istio/test-infra/pull/1020, https://github.com/istio/istio/pull/9577 & issue: https://github.com/istio/test-infra/issues/1018
   1. [ ] ~istio/cni change triggered~ -  This is no longer the plan
1. CircleCI istio/cni
    1.  [X] istio/cni e2e - Using DinD approach from the [kubeadm-dind-cluster (KDC) proj](https://github.com/kubernetes-sigs/kubeadm-dind-cluster)... see PR #62 
    2.  [X] Unit tests, lint
    3.  [X] Functional tests
1. [x] Documentation - https://github.com/istio/istio.io/pull/2902
   1. [x] Add info to istio.io (how to doc for alpha features?) -- https://github.com/istio/istio.io/pull/2902
      1. [x] installation options
      1. [x] hosted k8s specific info
      1. [ ] troubleshooting
   1. [X] istio/cni README
      1. [X] Clarify installation & current implementation behavior,  add new use cases
 1. [x] Necessary changes in release 1.1 branch

**Nice to have** features or functionality for 1.1 release. 
1. [ ] Finalize use-case scenarios
    1. [ ] upgrade
    1. [ ] coexistence
1. [ ] ~Prow job triggered by a change in the istio/cni repo -- https://github.com/istio/cni/issues/8~

**Comment by sdake** [comment]
For alpha features, just add the documentation as normal and the feature will be marked alpha in the feature status page here prior to release:

https://preliminary.istio.io/about/feature-stages/

**Comment by john-a-joyce** [comment]
All required milestones have been met,  although troubleshooting is maybe a still a bit weak.
